---
abstract: 'Build JavaScript distributions for JSAN, which can be installed locally'
author:
  - 'Nickolay Platonov <nplatonov@cpan.org>'
build_requires:
  Capture::Tiny: 0.06
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-JSAN-Installable
provides:
  Module::Build::JSAN::Installable:
    file: lib/Module/Build/JSAN/Installable.pm
    version: 0.08
requires:
  JSON: 2.00
  Module::Build: 0.35
  Module::Build::JSAN: 0.05
  Path::Class: 0.16
  Text::Markdown: v1.0.26
  Text::MultiMarkdown: v1.0.29
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
